# Site settings
title: NumberHound
description: "A blog about sports and data storytelling, amongst other things."
url: "http://www.numberhound.com"
author:
  name: "Chris Smitten"
  email: "csmitten2@outlook.com"
  url: "http://www.numberhound.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
